### ISSUE TITLE
[BUG] BtWQuests: Dragonflight Doesn't Load in Dragonflight Beta 10.0.2 (46144)

### ISSUE THREAD

**Issue by Calesta** [Breeni/BtWQuestsDragonflight#1]
I have the latest BtWQuests (2.20.0) and the latest BTWQuests: Dragonflight (.03beta) installed on the Dragonflight Beta (10.0.2 (46144)).

In previous Dragonflight beta builds, both were working fine.  In the latest build, I noticed the BTWQuest: Dragonflight addon doesn't load.

![Addon List](https://user-images.githubusercontent.com/13042214/197911288-146b4a82-068a-4e4f-8a8d-4a76272a2b83.PNG)

When I open BTWQuests from the minimap icon, then it shows the interface but there are buttons labeled 'Load Addon' & 'View All' and checkboxes labeled 'Auto Load'.  I tried clicking / checking them all and nothing happened.

![BTW Quests Dragonflight](https://user-images.githubusercontent.com/13042214/197911779-b4fce65a-0669-44af-b154-c92d913d2076.PNG)

Reporting this for awareness and hoping that it's an easy fix.

**Comment by Breeni** [comment]
One of the recent beta builds broke everything, there is a new version (v2.22.0) of the core addon on the way but it may take a while before it becomes available due to prepatch release. Please let me know if it persists.
