### ISSUE TITLE
Some quests aren't available.

### ISSUE THREAD

**Issue by emotionbug** [Breeni/BtWQuestsDragonflight#10]
Hello.
These quests aren't available anymore.

https://www.wowhead.com/quest=72658/flightstones
https://www.wowhead.com/quest=75506/shadowflame-crests
https://www.wowhead.com/quest=75507/catching-up-with-friends

**Comment by Breeni** [comment]
Thanks for letting me know, I've released an update (v10.0) with these quests removed.

**Comment by emotionbug** [comment]
Thank you!
