### ISSUE TITLE
Bug: Quests showing up limited to class whilst not being said class

### ISSUE THREAD

**Issue by dapal-003** [Breeni/BtWQuestsDragonflight#2]
Under The Waking Shores in the Wingrest Embassy quest screen the quest "[Opportunities Abound](https://www.wowhead.com/quest=70042/opportunities-abound)" is shown to non rouge classes. I am seeing it on my druid who can't accept said quest.

**Comment by xXEliotXx** [comment]
Also happening for myself, on hunter.

**Comment by Breeni** [comment]
I've pushed a new version (v1.1) that should solve this issue, please let me know if it persists.

**Comment by BalouhWoW** [comment]
Both quests are removed with version 1.1 but the checkmark is missing for that card. 
btw nice images for zones ;)
