### ISSUE TITLE
Wingrest Embassy doesn't show as finished

### ISSUE THREAD

**Issue by zap-py** [Breeni/BtWQuestsDragonflight#3]
Hi,

I finished the category "The Waking Shores" -> "Wingrest Embassy".
But there seems to be an issue with it getting marked as finished.
As you can see I did all the quests it contains but it still shows as an unfinished category.

Maybe there is a quest-related reason I don't know but I think I did everything and it should tick off.

![grafik](https://user-images.githubusercontent.com/17334481/205736483-c6272547-193e-4ce3-a8e6-3dea2a936b01.png)

![grafik](https://user-images.githubusercontent.com/17334481/205736019-864775ee-ad14-45fa-8435-b0d5d2290831.png)

**Comment by Breeni** [comment]
I've released a new version (v2.25.0) that should fix this issue, please let me know if it persists.

**Comment by zapp2me** [comment]
The issue is fixed with the latest release. 
Thank you very much! And thanks for making one of my favorite addons for leveling!
