### ISSUE TITLE
'The Silver Purpose' Questline Showing as "The Chieftain's Duty'

### ISSUE THREAD

**Issue by SisrenWarrior** [Breeni/BtWQuestsDragonflight#4]
The Valdrakken Accord renown 12 questline 'The Silver Purpose' shows up in the list as the Iskaara renown 11 questline 'The Chieftain's Duty'. All quests and functionality are correct for 'The Silver Purpose', it's just the label that's wrong.

![WoWScrnShot_010123_234150](https://user-images.githubusercontent.com/119249442/210195747-d19623d8-5bd8-4729-9761-9f894ae73ff7.jpg)
![WoWScrnShot_010123_234217](https://user-images.githubusercontent.com/119249442/210195767-85d11fc1-b876-4721-9818-b5ef2aef102d.jpg)
![WoWScrnShot_010123_234236](https://user-images.githubusercontent.com/119249442/210195775-81d6a73f-9a60-49bd-a59d-c73dcc4dd75e.jpg)

**Comment by Breeni** [comment]
I've pushed a new version (v1.4) that should solve this issue, please let me know if it persists.
